meta_product_name: "Savruna"
meta_title: "Savruna - Zvyras, kretinga klaipeda, vezamas zvyras smelis juodzemis"
meta_description: "Zvyras, kretinga klaipeda, vezamas zvyras smelis juodzemis"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
